// Generated by gencpp from file amiro_msgs/Int32MultiArrayStamped.msg
// DO NOT EDIT!


#ifndef AMIRO_MSGS_MESSAGE_INT32MULTIARRAYSTAMPED_H
#define AMIRO_MSGS_MESSAGE_INT32MULTIARRAYSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Int32MultiArray.h>

namespace amiro_msgs
{
template <class ContainerAllocator>
struct Int32MultiArrayStamped_
{
  typedef Int32MultiArrayStamped_<ContainerAllocator> Type;

  Int32MultiArrayStamped_()
    : header()
    , array()  {
    }
  Int32MultiArrayStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , array(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Int32MultiArray_<ContainerAllocator>  _array_type;
  _array_type array;





  typedef boost::shared_ptr< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> const> ConstPtr;

}; // struct Int32MultiArrayStamped_

typedef ::amiro_msgs::Int32MultiArrayStamped_<std::allocator<void> > Int32MultiArrayStamped;

typedef boost::shared_ptr< ::amiro_msgs::Int32MultiArrayStamped > Int32MultiArrayStampedPtr;
typedef boost::shared_ptr< ::amiro_msgs::Int32MultiArrayStamped const> Int32MultiArrayStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace amiro_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'amiro_msgs': ['/homes/joschroeder/github/nightwatcher/catkin_ws/src/amiro_robot/amiro_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6518a46d079512f8a23203836b73fa9";
  }

  static const char* value(const ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6518a46d079512fULL;
  static const uint64_t static_value2 = 0x8a23203836b73fa9ULL;
};

template<class ContainerAllocator>
struct DataType< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amiro_msgs/Int32MultiArrayStamped";
  }

  static const char* value(const ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Stamped int32 multi array\n\
\n\
std_msgs/Header header\n\
std_msgs/Int32MultiArray array\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
int32[]           data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Int32MultiArrayStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amiro_msgs::Int32MultiArrayStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "array: ";
    s << std::endl;
    Printer< ::std_msgs::Int32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.array);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMIRO_MSGS_MESSAGE_INT32MULTIARRAYSTAMPED_H
